version: "3.8"
services:
  mongo-db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-db:/data/db
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://mongo-db:27017/pets-api
volumes:
  mongo-db: {}
